### PR TITLE
#95 MainTest is turned on

### PR DESCRIPTION
**Pull request by darkled**
Some changes are made, but for the moment MainTest is not passed due to AmazonServiceException

### CODE REVIEW

**Comment by longtimeago** [comment]
@darkled any news?

**Comment by darkled** [comment]
@longtimeago not yet, I am still working on it.

**Comment by longtimeago** [comment]
@darkled any progress?

**Comment by darkled** [comment]
@longtimeago not yet, the impediment is still opened.

**Comment by longtimeago** [comment]
@darkled I propose to close this PR, as it will be outdated as soon as https://github.com/yegor256/s3auth/issues/254 will be done. What do you think?

**Comment by darkled** [comment]
@longtimeago I think it makes sense, closing PR now.

**Comment by davvd** [comment]
@longtimeago Much appreciated! **18 mins** was added to your account, payment ID `51638988`

+18 added to your rating, at the moment it is: [+1788](http://www.netbout.com/b/35024?open=rating)

**Pull request closed without merging**
