### PR TITLE
#221 - one-time variable in HttpResponse#send()

### PR DESCRIPTION
**Pull request by maurezen**
Inlined the variable.

### CODE REVIEW

**Comment by davvd** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by maurezen** [comment]
@davvd any progress with that?

**Comment by maurezen** [comment]
@davvd @yegor256 please find someone to review this PR. It's been quite a while.

**Comment by davvd** [comment]
@longtimeago please review,thanks

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by davvd** [comment]
@longtimeago paid, thanks, added **21 mins** to your account, payment `50525547`

added +21 to your rating, now it is equal to [+1177](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
