### PR TITLE
#90: DefaultDynamo: Would be nice to migrate to jcabi-dynamo

### PR DESCRIPTION
**Pull request by pinaf**
- added dependency to jcabi-dynamo 0.18.1
 - DefaultDynamo
  - use jcabi-dynamo instead of Amazon Dynamo API
  - no longer use Client, instead use Region from jcabi-dynamo
 - DefaultDynamoTest
  - use Mock Region instead of Mock AmazonDynamoDB class
  - added puzzle for getting H2Data backend to work with special characters ( see [jcabi-dynamo issue 7](https://github.com/jcabi/jcabi-dynamo/issues/7) )

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by davvd** [comment]
@longtimeago it's yours,please review

**Comment by longtimeago** [comment]
@pinaf Good job! Several remarks:
1) You forgot to remove initial todo
https://github.com/yegor256/s3auth/pull/261/files#diff-a5ab9f70e1bd5cf6ea720796ec43184fR61
Please, remove it unless you want to wait a payment for a long time :)
2) We can't just ignore the test. To avoid unsupported chars (```.```) just replace it with underscore.
Test would fail by another reason (kinda ```java.sql.SQLException: org.h2.jdbc.JdbcSQLException: Column "DOMAIN" not found```) and you may guess why.

**Comment by pinaf** [comment]
@longtimeago thanks!
1) Oops!
2) Well what happened here is that there existed a test that used directly the AmazonDynamoDB API, which is exactly what I'm hiding here. So what I did was replace the old test by the new one I wrote that uses the new `H2Data`, and here the column names became an issue because of the special characters.  If I try to replace on the fly with an underscore I would have to do it in multiple places: everywhere the `DefaultDynamo.USER`, `DefaultDynamo.NAME`, etc, fields are used!! Not sure this is a good idea... Also, replacing the actual values of those fields is something carlosmiranda warned against when dpisarenko tried it: https://github.com/yegor256/s3auth/pull/239#discussion_r22417175
Are you suggesting I just replace with underscored in the test when the the temporary DB is created and leave the test failing?

**Comment by longtimeago** [comment]
@pinaf You are right. We can't change the test. Unfortunately, I can't accept this PR with ignored test. Let's wait for the #7. It will be finished soon and you will be able to continue here.

**Comment by longtimeago** [comment]
@davvd we have to wait for #7

**Comment by pinaf** [comment]
@longtimeago I thought ignoring a test in this situation was fine: http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by longtimeago** [comment]
@pinaf let's ask author :)
@yegor256 should we accept current PR with ignored test?

**Comment by pinaf** [comment]
@longtimeago lol OutOfMemory error in Travis:)

**Comment by longtimeago** [comment]
@pinaf I saw that. Looks like they forgot to pay the bill :)

**Comment by davvd** [comment]
> @davvd we have to wait for #7

@longtimeago issue #7 is closed already

**Comment by pinaf** [comment]
@davvd it's [issue 7 from jcabi-dynamo](https://github.com/jcabi/jcabi-dynamo/issues/7). looks like it was just closed :)

**Comment by pinaf** [comment]
@longtimeago should I unignore the test and commit again? I guess first merge from master into my branch.

**Comment by yegor256** [comment]
@pinaf yes, indeed, that issue is closed and we can use the latest version of jcabi-dynamo, where the problem is fixed

**Comment by pinaf** [comment]
@yegor256 @longtimeago unfortunately the fix only dealt with table names. column names are also needed. Please see this new issue [jcabi-dynamo#28](https://github.com/jcabi/jcabi-dynamo/issues/28)

@davvd we need to wait for this new issue

**Comment by yegor256** [comment]
@davvd we need more time here

**Comment by davvd** [comment]
> @davvd we need more time here

@yegor256 sure, take your time

**Comment by pinaf** [comment]
@longtimeago @yegor256 you guys sure I can't just leave the test ignored with the puzzle? this issue is taking forever because of the jcabi-dynamo dependency.

**Comment by pinaf** [comment]
merged with master...

**Comment by yegor256** [comment]
@pinaf I'm always in favor of puzzles, they help us to merge code faster

**Comment by longtimeago** [comment]
@pinaf I agree. Let's merge

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by pinaf** [comment]
@longtimeago @yegor256 thanks guys!

**Comment by davvd** [comment]
@longtimeago Thank you, I have added **20 mins** to your account in payment/transaction "`52363341`". +20 added to your rating, current score is: [+2016](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Comment by yegor256** [comment]
@pinaf now the site is down :( investigating...

**Comment by yegor256** [comment]
@rultor try to deploy again

**Comment by yegor256** [comment]
we're up again. thanks all

**Pull request merged**
