### PR TITLE
#279 deleted duplicate declaration of plugins

### PR DESCRIPTION
**Pull request by simonjenga**
Should have multiple execution declarations. Not plugin declarations.

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@pinaf this pull request is for you,please review

**Comment by pinaf** [comment]
@simonjenga what issue is this one for?

**Comment by pinaf** [comment]
@simonjenga travis build failed and locally I can't build it either - Out of memory.
>
Exception in thread "main" java.lang.OutOfMemoryError: PermGen space

**Comment by simonjenga** [comment]
@pinaf Travis build fails because of some other reasons (```com.s3auth.relay.HttpFacadeTest```)

Please post the full stack trace to your build failure message.

I would advise that if you still can't build the project, it would be a good idea for you to request @davvd to assign this PR to someone else to do the CR.

**Comment by pinaf** [comment]
@simonjenga what issue is this for? also, I ran your branch on another machine and got this error:
>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] s3auth ............................................ FAILURE [3.320s]
[INFO] s3auth-hosts ...................................... SKIPPED
[INFO] s3auth-relay ...................................... SKIPPED
[INFO] s3auth-rest ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.822s
[INFO] Finished at: Wed Mar 25 12:11:34 BRT 2015
[INFO] Final Memory: 14M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromChildren(CollectionConverter.java:157)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:112)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:289)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:161)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:567)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:529)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	... 16 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by pinaf** [comment]
@simonjenga to be fair master also has the same error.

**Comment by pinaf** [comment]
@yegor256 master looks broken to me. is it just me?

**Comment by simonjenga** [comment]
@pinaf what version of Maven are you using?

**Comment by pinaf** [comment]
@simonjenga yeah I think thats the issue. updating now.

**Comment by simonjenga** [comment]
Take a look at this: https://github.com/yegor256/rexsl/issues/765

**Comment by pinaf** [comment]
@simonjenga ok it builds but runs out of memory also. here is the end of the log.
>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] s3auth ............................................ SUCCESS [01:38 min]
[INFO] s3auth-hosts ...................................... SUCCESS [05:44 min]
[INFO] s3auth-relay ...................................... SUCCESS [05:50 min]
[INFO] s3auth-rest ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26:46 min
[INFO] Finished at: 2015-03-25T13:20:11-03:00
[INFO] Final Memory: 62M/959M
[INFO] ------------------------------------------------------------------------
[ERROR] PermGen space -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
---------------------------------------------------
constituent[0]: file:/usr/share/maven3/lib/org.eclipse.sisu.plexus-0.0.0.M5.jar
constituent[1]: file:/usr/share/maven3/lib/wagon-http-2.6-shaded.jar
constituent[2]: file:/usr/share/maven3/lib/aopalliance-1.0.jar
constituent[3]: file:/usr/share/maven3/lib/maven-aether-provider-3.2.1.jar
constituent[4]: file:/usr/share/maven3/lib/maven-settings-builder-3.2.1.jar
constituent[5]: file:/usr/share/maven3/lib/plexus-cipher-1.7.jar
constituent[6]: file:/usr/share/maven3/lib/maven-plugin-api-3.2.1.jar
constituent[7]: file:/usr/share/maven3/lib/aether-util-0.9.0.M2.jar
constituent[8]: file:/usr/share/maven3/lib/javax.inject-1.jar
constituent[9]: file:/usr/share/maven3/lib/plexus-sec-dispatcher-1.3.jar
constituent[10]: file:/usr/share/maven3/lib/cdi-api-1.0.jar
constituent[11]: file:/usr/share/maven3/lib/plexus-component-annotations-1.5.5.jar
constituent[12]: file:/usr/share/maven3/lib/maven-artifact-3.2.1.jar
constituent[13]: file:/usr/share/maven3/lib/jsoup-1.7.2.jar
constituent[14]: file:/usr/share/maven3/lib/commons-cli-1.2.jar
constituent[15]: file:/usr/share/maven3/lib/aether-spi-0.9.0.M2.jar
constituent[16]: file:/usr/share/maven3/lib/slf4j-simple-1.7.5.jar
constituent[17]: file:/usr/share/maven3/lib/commons-lang-2.6.jar
constituent[18]: file:/usr/share/maven3/lib/maven-model-builder-3.2.1.jar
constituent[19]: file:/usr/share/maven3/lib/maven-compat-3.2.1.jar
constituent[20]: file:/usr/share/maven3/lib/plexus-utils-3.0.17.jar
constituent[21]: file:/usr/share/maven3/lib/guava-14.0.1.jar
constituent[22]: file:/usr/share/maven3/lib/wagon-provider-api-2.6.jar
constituent[23]: file:/usr/share/maven3/lib/commons-io-2.2.jar
constituent[24]: file:/usr/share/maven3/lib/slf4j-api-1.7.5.jar
constituent[25]: file:/usr/share/maven3/lib/sisu-guice-3.1.3-no_aop.jar
constituent[26]: file:/usr/share/maven3/lib/wagon-file-2.6.jar
constituent[27]: file:/usr/share/maven3/lib/wagon-http-shared-2.6.jar
constituent[28]: file:/usr/share/maven3/lib/maven-embedder-3.2.1.jar
constituent[29]: file:/usr/share/maven3/lib/maven-settings-3.2.1.jar
constituent[30]: file:/usr/share/maven3/lib/maven-model-3.2.1.jar
constituent[31]: file:/usr/share/maven3/lib/org.eclipse.sisu.inject-0.0.0.M5.jar
constituent[32]: file:/usr/share/maven3/lib/aether-impl-0.9.0.M2.jar
constituent[33]: file:/usr/share/maven3/lib/maven-core-3.2.1.jar
constituent[34]: file:/usr/share/maven3/lib/aether-connector-wagon-0.9.0.M2.jar
constituent[35]: file:/usr/share/maven3/lib/jsr250-api-1.0.jar
constituent[36]: file:/usr/share/maven3/lib/aether-api-0.9.0.M2.jar
constituent[37]: file:/usr/share/maven3/lib/maven-repository-metadata-3.2.1.jar
constituent[38]: file:/usr/share/maven3/lib/plexus-interpolation-1.19.jar
constituent[39]: file:/usr/share/maven3/conf/logging/
---------------------------------------------------
Exception in thread "main" java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	at org.eclipse.sisu.inject.MildElements.iterator(MildElements.java:74)
	at org.eclipse.sisu.inject.RankedBindings.remove(RankedBindings.java:70)
	at org.eclipse.sisu.inject.InjectorPublisher.unsubscribe(InjectorPublisher.java:81)
	at org.eclipse.sisu.inject.RankedBindings.remove(RankedBindings.java:123)
	at org.eclipse.sisu.inject.DefaultBeanLocator.remove(DefaultBeanLocator.java:105)
	at org.eclipse.sisu.inject.DefaultBeanLocator.clear(DefaultBeanLocator.java:118)
	at org.codehaus.plexus.DefaultPlexusContainer.dispose(DefaultPlexusContainer.java:588)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:240)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by pinaf** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@pinaf **23 mins** sent to your balance (ID `AP-8RR08001YU6524607`), many thanks! It took 64 hours and 34 mins.... extra minutes for review comments (c=8)... +23 to your rating, your total score is [+5354](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
