### PR TITLE
modified .gitignore with more files

### PR DESCRIPTION
**Pull request by simonjenga**
```
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        bin/

nothing added to commit but untracked files present (use "git add" to track)
```

### CODE REVIEW

**Comment by davvd** [comment]
@simonjenga Thanks, I will find someone to review this PR soon

**Comment by davvd** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by simonjenga** [comment]
@davvd @yegor256 A decision needs to be made on the status of this PR ASAP.
It is rather small but getting old.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by simonjenga** [comment]
@davvd @yegor256
I am closing this PR. Please make this small change i had requested in the .gitignore file in order to stop Git from tracking the bin folder.

**Comment by davvd** [comment]
> @davvd @yegor256
> I am closing this PR. Please make this small change i had requested in the .gitignore file in order to stop Git from tracking the bin folder.

@simonjenga OK

**Comment by davvd** [comment]
@yegor256 Many thanks! **17 mins** were added to your account in Transaction ID `000-eb982303` (task took 7822 hours and 10 mins)... extra minutes for review comments (c=2)... +17 added to your rating, current score is: [+146](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
