### PR TITLE
191

### PR DESCRIPTION
**Pull request by wentwog**
changes:
1) we should import maven properties into System properties via surefire plugin configuration. 
Since System properties set by jcabi-ssl-maven-plugin are not visible in the tests execution. I suppose, this is due to test are being run within different jvm.

2) added assertions for keystore and truststore parameters.
To provide for diagnosing problem faster in the future, if it would arise again.

### CODE REVIEW

**Comment by krzyk** [comment]
@wentwog 0.10 version of jcabi-ssl-maven-plugin has been released, please upgrade the code with it (and maybe merge master if there are any changes)

**Comment by wentwog** [comment]
@krzyk thanks, checking

**Comment by wentwog** [comment]
@krzyk another issue in jcabi-ssl-maven-plugin blocks this one. The details are in the issue itself.

**Comment by krzyk** [comment]
@wentwog let me know when the other issue is closed, so I can proceed here

**Comment by wentwog** [comment]
@krzyk ok

**Comment by wentwog** [comment]
build failed due to OutOfMemoryEx. I suppose it's the build server load issue. Trying to close/open PL to trigger new buid

**Comment by krzyk** [comment]
@wentwog there is test failing in travis

**Comment by wentwog** [comment]
@krzyk yes, I'm investigating whether it is a separate issue or not.

**Comment by wentwog** [comment]
@krzyk the original SSLHandshakeException is fixed and now we have the other issue - the response body content doesn't match the expected result.
So, I think the initial problem is solved and we should open a new ticket for the new problem.
Do you agree?

**Comment by krzyk** [comment]
@wentwog but that still leaves the build in a failed state, so let's add @Ignore to the test that is failing and create a todo for resolving the problem

**Comment by wentwog** [comment]
@krzyk sure, done.

**Comment by wentwog** [comment]
@krzyk done

**Comment by krzyk** [comment]
@wentwog please try to rephrase the problem, not just the error output. Maybe *Test below fails to retrieve HTTPS content (it returns an empty string instead "secured"), please fix that and enable this test.*

**Comment by wentwog** [comment]
@krzyk done

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@krzyk thanks, paid, **20 mins** to your account, payment ID is `51295767`. +20 added to your rating, at the moment it is: [+3669](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor please deploy

**Pull request merged**
