### PR TITLE
#191 Removed Ignore annotation

### PR DESCRIPTION
**Pull request by carlosmiranda**
@yegor256 I haven't been able to trace this error since it always works when I try to build it. Let's try it on new Rultor?

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor let's try to merge again

**Comment by yegor256** [comment]
@carlosmiranda are you planning to finish this? If not, please close it

**Comment by carlosmiranda** [comment]
My bad, sorry. It has been addressed separately, closing this now.

**Comment by davvd** [comment]
@yegor256 **17 mins** was added to your account, many thanks for your contribution!... +17 added to your rating, current score is: [+6017](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
