### PR TITLE
#200 Migrate s3auth-rest integration tests to CasperJS

### PR DESCRIPTION
**Pull request by palyuga**

### CODE REVIEW

**Comment by davvd** [comment]
I'll find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by davvd** [comment]
@yegor256 review this one, please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by davvd** [comment]
@yegor256 I just added **19 mins** to your account, many thanks for your contribution..

+19 added to your rating, at the moment it is: [+4515](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
