### PR TITLE
(#317) Fixed XML formatting for all XMLs and XSLs

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* Is for #317
* Fixes formatting on XMLs and XSLs in preparation for upgrade to jcabi-parent v0.49.3
* Does NOT upgrade jcabi-parent version because the build keeps failing for other issues.
* Leaves puzzle in the root-level `pom.xml` to continue fixing stuff in order to upgrade jcabi-parent version

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#370](https://github.com/yegor256/s3auth/issues/370) is now in scope, role is `REV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RP1J1CH](https://www.0crat.com/p/C3RP1J1CH), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="931479052">
   <created>2018-04-03T14:48:44.449Z</created>
   <type>Register impediment</type>
   <token>github;yegor256/s3auth;348;378272835</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/s3auth#348</param>
      <param name="repo">yegor256/s3auth</param>
      <param name="issue">348</param>
      <param name="comment">378272835</param>
   </params>
</claim>

com.zerocracy.pm.Claims[111] java.lang.IllegalStateException: Duplicate claims are not allowed in [C3RP1J1CH](https://www.0crat.com/p/C3RP1J1CH), can't add this XML:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="931479052">
   <created>2018-04-03T14:48:44.449Z</created>
   <type>Register impediment</type>
   <token>github;yegor256/s3auth;348;378272835</token>
   <author>llorllale</author>
   <params>
      <param name="job">gh:yegor256/s3auth#348</param>
      <param name="repo">yegor256/s3auth</param>
      <param name="issue">348</param>
      <param name="comment">378272835</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@rultor merge

**Comment by llorllale** [comment]
@yegor256 fixed conflicts, please merge.

Note: the travis build is failing because casperjs is no longer being installed in the travis build after [this](https://github.com/yegor256/s3auth/commit/a1f5f6061c9825bf08efde633692be71739580a2#diff-5db1d31b4191db67a842fe41e2a0c4d6) change.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#370](https://github.com/yegor256/s3auth/issues/370) is now out of scope

**Pull request merged**
