### PR TITLE
First attempt at implementing task #90 (migration of DefaultDynamo to JCabi-Dynamo)

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue: https://github.com/yegor256/s3auth/issues/90#issuecomment-68104765

### CODE REVIEW

**Comment by krzyk** [comment]
@davvd waiting for jcabi/jcabi-ssl-maven-plugin#3

**Comment by dpisarenko** [comment]
@longtimeago Sorry for the dealy. Yes, the more recent pull request is the right one ( https://github.com/yegor256/s3auth/pull/239 ).

**Comment by longtimeago** [comment]
@krzyk Thank you!
@dpisarenko Please, close this PR as you have new one for the issue

**Comment by davvd** [comment]
@krzyk **22 mins** added to your account (payment number `49764315`), many thanks for your contribution!; added +22 to your rating, now it is equal to [+1297](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
