### PR TITLE
#375 Update copyright notice

### PR DESCRIPTION
**Pull request by carlosmiranda**
#375 Update copyright notice to 2012-2019.

### CODE REVIEW

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#377](https://github.com/yegor256/s3auth/issues/377) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#377` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#377](https://github.com/yegor256/s3auth/issues/377) is now out of scope

**Pull request merged**
