### PR TITLE
Attempt at bugfix s3auth-260.

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue: https://github.com/yegor256/s3auth/issues/260

### CODE REVIEW

**Comment by davvd** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@krzyk review this one,please

**Comment by krzyk** [comment]
@dpisarenko travis build fails with checkstyle problems

**Comment by krzyk** [comment]
@dpisarenko please have a look at what pinaf wrote https://github.com/yegor256/s3auth/issues/260#issuecomment-70944169

Constructor should still fail if the MANIFEST is missing, so you have to place it in s3auth-hosts (look at similar file in s3auth-rest (https://github.com/yegor256/s3auth/blob/master/s3auth-rest/src/test/resources/META-INF/MANIFEST.MF)

**Comment by dpisarenko** [comment]
@krzyk I fixed the issues reported by you and pinaf. Please review again. Thanks.

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@krzyk thanks, paid, **18 mins** to your account, payment ID is `50663442`... added +18 to your rating, now it is equal to [+2706](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
